
package cn.topca.tca.ra.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-13T17:48:42.293+08:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "RaServiceUnavailable", targetNamespace = "http://service.ra.tca.topca.cn/")
public class RaServiceUnavailable_Exception extends Exception {
    
    private cn.topca.tca.ra.service.RaServiceUnavailable raServiceUnavailable;

    public RaServiceUnavailable_Exception() {
        super();
    }
    
    public RaServiceUnavailable_Exception(String message) {
        super(message);
    }
    
    public RaServiceUnavailable_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public RaServiceUnavailable_Exception(String message, cn.topca.tca.ra.service.RaServiceUnavailable raServiceUnavailable) {
        super(message);
        this.raServiceUnavailable = raServiceUnavailable;
    }

    public RaServiceUnavailable_Exception(String message, cn.topca.tca.ra.service.RaServiceUnavailable raServiceUnavailable, Throwable cause) {
        super(message, cause);
        this.raServiceUnavailable = raServiceUnavailable;
    }

    public cn.topca.tca.ra.service.RaServiceUnavailable getFaultInfo() {
        return this.raServiceUnavailable;
    }
}
