package cn.topca.tca.ra.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-13T17:48:42.303+08:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://service.ra.tca.topca.cn/", name = "UserAPIServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface UserAPIServicePortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryCertByCertId", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.QueryCertByCertId")
    @WebMethod
    @ResponseWrapper(localName = "queryCertByCertIdResponse", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.QueryCertByCertIdResponse")
    public cn.topca.tca.ra.service.QueryCertResult queryCertByCertId(
        @WebParam(name = "certId", targetNamespace = "")
        int certId,
        @WebParam(name = "accountHash", targetNamespace = "")
        java.lang.String accountHash,
        @WebParam(name = "json", targetNamespace = "")
        java.lang.String json
    ) throws RaServiceUnavailable_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "downloadCRL", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.DownloadCRL")
    @WebMethod
    @ResponseWrapper(localName = "downloadCRLResponse", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.DownloadCRLResponse")
    public java.lang.String downloadCRL(
        @WebParam(name = "accountHash", targetNamespace = "")
        java.lang.String accountHash
    ) throws RaServiceUnavailable_Exception;

    @RequestWrapper(localName = "enrollCert", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.EnrollCert")
    @WebMethod
    @ResponseWrapper(localName = "enrollCertResponse", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.EnrollCertResponse")
    public void enrollCert(
        @WebParam(name = "userInfo", targetNamespace = "")
        cn.topca.tca.ra.service.UserInfo userInfo,
        @WebParam(name = "certReqBuf", targetNamespace = "")
        java.lang.String certReqBuf,
        @WebParam(name = "certReqChallenge", targetNamespace = "")
        java.lang.String certReqChallenge,
        @WebParam(name = "accountHash", targetNamespace = "")
        java.lang.String accountHash,
        @WebParam(name = "json", targetNamespace = "")
        java.lang.String json
    ) throws RaServiceUnavailable_Exception;

    @RequestWrapper(localName = "unsuspendCert", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.UnsuspendCert")
    @WebMethod
    @ResponseWrapper(localName = "unsuspendCertResponse", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.UnsuspendCertResponse")
    public void unsuspendCert(
        @WebParam(name = "serialNumber", targetNamespace = "")
        java.lang.String serialNumber,
        @WebParam(name = "accountHash", targetNamespace = "")
        java.lang.String accountHash,
        @WebParam(name = "json", targetNamespace = "")
        java.lang.String json
    ) throws RaServiceUnavailable_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryCerts", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.QueryCerts")
    @WebMethod
    @ResponseWrapper(localName = "queryCertsResponse", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.QueryCertsResponse")
    public cn.topca.tca.ra.service.QueryCertResult queryCerts(
        @WebParam(name = "userInfo", targetNamespace = "")
        cn.topca.tca.ra.service.UserInfo userInfo,
        @WebParam(name = "certInfo", targetNamespace = "")
        cn.topca.tca.ra.service.CertInfo certInfo,
        @WebParam(name = "pageIndex", targetNamespace = "")
        int pageIndex,
        @WebParam(name = "pageSize", targetNamespace = "")
        int pageSize,
        @WebParam(name = "sqlTemplateFileName", targetNamespace = "")
        java.lang.String sqlTemplateFileName,
        @WebParam(name = "nextResultTag", targetNamespace = "")
        java.lang.String nextResultTag,
        @WebParam(name = "totalTag", targetNamespace = "")
        java.lang.String totalTag,
        @WebParam(name = "accountHash", targetNamespace = "")
        java.lang.String accountHash
    ) throws RaServiceUnavailable_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "renewCertAA", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.RenewCertAA")
    @WebMethod
    @ResponseWrapper(localName = "renewCertAAResponse", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.RenewCertAAResponse")
    public cn.topca.tca.ra.service.CertInfo renewCertAA(
        @WebParam(name = "userInfo", targetNamespace = "")
        cn.topca.tca.ra.service.UserInfo userInfo,
        @WebParam(name = "origin", targetNamespace = "")
        cn.topca.tca.ra.service.CertInfo origin,
        @WebParam(name = "accountHash", targetNamespace = "")
        java.lang.String accountHash,
        @WebParam(name = "aaCheckPoint", targetNamespace = "")
        java.lang.String aaCheckPoint,
        @WebParam(name = "passCode", targetNamespace = "")
        java.lang.String passCode,
        @WebParam(name = "json", targetNamespace = "")
        java.lang.String json
    ) throws RaServiceUnavailable_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "downloadDeltaCRL", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.DownloadDeltaCRL")
    @WebMethod
    @ResponseWrapper(localName = "downloadDeltaCRLResponse", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.DownloadDeltaCRLResponse")
    public java.lang.String downloadDeltaCRL(
        @WebParam(name = "accountHash", targetNamespace = "")
        java.lang.String accountHash
    ) throws RaServiceUnavailable_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "downloadCA", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.DownloadCA")
    @WebMethod
    @ResponseWrapper(localName = "downloadCAResponse", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.DownloadCAResponse")
    public java.lang.String downloadCA(
        @WebParam(name = "accountHash", targetNamespace = "")
        java.lang.String accountHash
    ) throws RaServiceUnavailable_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "doScript", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.DoScript")
    @WebMethod
    @ResponseWrapper(localName = "doScriptResponse", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.DoScriptResponse")
    public java.lang.String doScript(
        @WebParam(name = "scriptName", targetNamespace = "")
        java.lang.String scriptName,
        @WebParam(name = "jsonMap", targetNamespace = "")
        java.lang.String jsonMap
    ) throws RaServiceUnavailable_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "pickupCert", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.PickupCert")
    @WebMethod
    @ResponseWrapper(localName = "pickupCertResponse", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.PickupCertResponse")
    public cn.topca.tca.ra.service.CertInfo pickupCert(
        @WebParam(name = "certPin", targetNamespace = "")
        java.lang.String certPin,
        @WebParam(name = "certReqChallenge", targetNamespace = "")
        java.lang.String certReqChallenge,
        @WebParam(name = "certReqBuf", targetNamespace = "")
        java.lang.String certReqBuf,
        @WebParam(name = "accountHash", targetNamespace = "")
        java.lang.String accountHash,
        @WebParam(name = "json", targetNamespace = "")
        java.lang.String json
    ) throws RaServiceUnavailable_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryCertBySerialNumber", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.QueryCertBySerialNumber")
    @WebMethod
    @ResponseWrapper(localName = "queryCertBySerialNumberResponse", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.QueryCertBySerialNumberResponse")
    public cn.topca.tca.ra.service.QueryCertResult queryCertBySerialNumber(
        @WebParam(name = "serialNumber", targetNamespace = "")
        java.lang.String serialNumber,
        @WebParam(name = "accountHash", targetNamespace = "")
        java.lang.String accountHash,
        @WebParam(name = "json", targetNamespace = "")
        java.lang.String json
    ) throws RaServiceUnavailable_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "synchroTemplate", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.SynchroTemplate")
    @WebMethod
    @ResponseWrapper(localName = "synchroTemplateResponse", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.SynchroTemplateResponse")
    public cn.topca.tca.ra.service.AccountConfigResult synchroTemplate(
        @WebParam(name = "accountHash", targetNamespace = "")
        java.lang.String accountHash
    ) throws RaServiceUnavailable_Exception;

    @RequestWrapper(localName = "renewCert", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.RenewCert")
    @WebMethod
    @ResponseWrapper(localName = "renewCertResponse", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.RenewCertResponse")
    public void renewCert(
        @WebParam(name = "userInfo", targetNamespace = "")
        cn.topca.tca.ra.service.UserInfo userInfo,
        @WebParam(name = "origin", targetNamespace = "")
        cn.topca.tca.ra.service.CertInfo origin,
        @WebParam(name = "accountHash", targetNamespace = "")
        java.lang.String accountHash,
        @WebParam(name = "json", targetNamespace = "")
        java.lang.String json
    ) throws RaServiceUnavailable_Exception;

    @RequestWrapper(localName = "revokeCert", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.RevokeCert")
    @WebMethod
    @ResponseWrapper(localName = "revokeCertResponse", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.RevokeCertResponse")
    public void revokeCert(
        @WebParam(name = "serialNumber", targetNamespace = "")
        java.lang.String serialNumber,
        @WebParam(name = "certReqChallenge", targetNamespace = "")
        java.lang.String certReqChallenge,
        @WebParam(name = "certRevokeReason", targetNamespace = "")
        java.lang.String certRevokeReason,
        @WebParam(name = "accountHash", targetNamespace = "")
        java.lang.String accountHash,
        @WebParam(name = "json", targetNamespace = "")
        java.lang.String json
    ) throws RaServiceUnavailable_Exception;

    @RequestWrapper(localName = "suspendCert", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.SuspendCert")
    @WebMethod
    @ResponseWrapper(localName = "suspendCertResponse", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.SuspendCertResponse")
    public void suspendCert(
        @WebParam(name = "serialNumber", targetNamespace = "")
        java.lang.String serialNumber,
        @WebParam(name = "accountHash", targetNamespace = "")
        java.lang.String accountHash,
        @WebParam(name = "json", targetNamespace = "")
        java.lang.String json
    ) throws RaServiceUnavailable_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "enrollCertAA", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.EnrollCertAA")
    @WebMethod
    @ResponseWrapper(localName = "enrollCertAAResponse", targetNamespace = "http://service.ra.tca.topca.cn/", className = "cn.topca.tca.ra.service.EnrollCertAAResponse")
    public cn.topca.tca.ra.service.CertInfo enrollCertAA(
        @WebParam(name = "userInfo", targetNamespace = "")
        cn.topca.tca.ra.service.UserInfo userInfo,
        @WebParam(name = "certReqBuf", targetNamespace = "")
        java.lang.String certReqBuf,
        @WebParam(name = "accountHash", targetNamespace = "")
        java.lang.String accountHash,
        @WebParam(name = "aaCheckPoint", targetNamespace = "")
        java.lang.String aaCheckPoint,
        @WebParam(name = "passCode", targetNamespace = "")
        java.lang.String passCode,
        @WebParam(name = "json", targetNamespace = "")
        java.lang.String json
    ) throws RaServiceUnavailable_Exception;
}
